# This is a basic workflow to help you get started with Actions

name: doRelease
on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  Build:
    # The type of runner that the job will run on
    #runs-on: windows-latest
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.7
      
      - name: Restore NuGet packages
        run: nuget restore Another-Mirai-Native.sln 
        
      - name: Restore DllExport
        run: .\DllExport -action Restore

      - name: Run MSBuild
        run: msbuild
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
             name: artifact
             path: | 
                   Another-Mirai-Native\bin\Debug\AnotherMiraiNative.exe
                   Another-Mirai-Native\bin\Debug\CQP.dll
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
                 Another-Mirai-Native\bin\Debug\AnotherMiraiNative.exe
                 Another-Mirai-Native\bin\Debug\CQP.dll
      - name: Copy
        run: |
            gh repo clone debumori-osc/another-mirai-native-release
            cd another-mirai-native-release
            rm AnotherMiraiNative.exe
            rm CQP.dll
            cd ..
            cp Another-Mirai-Native\bin\Debug\AnotherMiraiNative.exe another-mirai-native-release\AnotherMiraiNative.exe
            cp Another-Mirai-Native\bin\Debug\CQP.dll another-mirai-native-release\CQP.dll
            cd another-mirai-native-release
            git add .\CQP.dll
            git add .\AnotherMiraiNative.exe
            git commit -m "update"
            git push
            gh release create '${{ github.ref_name }}'
            
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      
